import React from 'react';
import { useQuery } from 'react-query';
import { gql } from 'graphql-request';
import { Post } from '~/__generated__/graphql';
import Header from '~/components/Header';
import Layout from '~/components/Layout';
import Seo from '~/components/Seo';
import PostItem from '~/components/PostsPage/PostItem';
import Tweet from '~/components/PostsPage/Tweet';

import { graphqlClient } from '~/lib/graphqlClient';
const Posts = () => {
  const { data, isLoading } = useQuery<Post[]>(
    'getPosts',
    async () => {
      const { getPosts } = await graphqlClient.request(gql`
        query {
          getPosts {
            id
            post
            terms {
              id
              name
            }
            users {
              id
              name
            }
          }
        }
      `);

      return getPosts;
    },
    // 指定した時間経過後に再度データのフェッチを行う
    { staleTime: 500000 },
  );

  return (
    <>
      <Seo title="Create Next App" description="Generated by create next app" />
      <Header />
      <Layout>
        <Tweet />
        {isLoading ? (
          <div>Loaging...</div>
        ) : (
          <div>
            {data?.map((e, i) => (
              <PostItem key={i} users={e.users} terms={e.terms} post={e.post} />
            ))}
          </div>
        )}
      </Layout>
    </>
  );
};

export default Posts;
