import React from 'react';
import { useQuery } from 'react-query';
import { gql } from 'graphql-request';
import { Post } from '~/__generated__/graphql';
import Header from '~/components/Header';
import Layout from '~/components/Layout';
import Seo from '~/components/Seo';
import Tweet from '~/components/Tweet';
import { graphqlClient } from '~/lib/graphqlClient';

const Posts = () => {
  const { data, isLoading } = useQuery<Post[]>(
    'getPosts',
    async () => {
      const { getPosts } = await graphqlClient.request(gql`
        query {
          getPosts {
            id
            post
            terms {
              id
              name
            }
            users {
              id
              name
            }
          }
        }
      `);

      return getPosts;
    },
    // 指定した時間経過後に再度データのフェッチを行う
    { staleTime: 500000 },
  );

  return (
    <>
      <Seo title="Create Next App" description="Generated by create next app" />
      <Header />
      <Layout>
        <Tweet />
        {isLoading ? (
          <div>Loaging...</div>
        ) : (
          <div>
            {data?.map((e, i) => (
              <div key={i} className="border rounded-md p-4 my-5">
                <div>
                  <a href={e.users?.name}>{e.users?.name}</a>
                  <a href={e.terms?.name}>{e.terms?.name}</a>
                </div>
                <div dangerouslySetInnerHTML={{ __html: e.post }} />
              </div>
            ))}
          </div>
        )}
      </Layout>
    </>
  );
};

export default Posts;
