import React from 'react';
import { useQuery } from 'react-query';
import { gql } from 'graphql-request';
import Header from '~/components/Header';
import Layout from '~/components/Layout';
import Seo from '~/components/Seo';
import { graphqlClient } from '~/lib/graphqlClient';
import { Post } from '~/__generated__/graphql';

const Posts = () => {
  const { data, isLoading } = useQuery<Post[]>('getPosts', async () => {
    const { getPosts } = await graphqlClient.request(gql`
      query {
        getPosts {
          id
          post
          terms {
            id
            name
          }
          users {
            id
            name
          }
        }
      }
    `);

    return getPosts;
  });

  return (
    <>
      <Seo title="Create Next App" description="Generated by create next app" />
      <Header />
      <Layout>
        {isLoading ? (
          <div>Loaging...</div>
        ) : (
          <div>
            {data?.map((e, i) => (
              <div key={i} className="border rounded-md p-4 my-5">
                <div>
                  <a href={e.users?.name}>{e.users?.name}</a>
                  <a href={e.terms?.name}>{e.terms?.name}</a>
                </div>
                <div dangerouslySetInnerHTML={{ __html: e.post }} />
              </div>
            ))}
          </div>
        )}
      </Layout>
    </>
  );
};

export default Posts;
